[package]
name = "eui"
version = "0.1.0"
edition = "2021"

[dependencies]
eui_derive = { path = "eui_derive" }

wasm-bindgen = "0.2"
serde = "*"
serde_json = "*"
postcard = { version = "1.0.5", features = ["experimental-derive", "use-std"] }


[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]