[package]
name = "eui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = "*"
serde_json = "*"
postcard = { version = "1.0.5", features = ["experimental-derive"] }
schemars = "0.8.12"