[package]
name = "dioxus_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.3"
dioxus-web = { version = "0.4.3", default-features = false, features = ["mounted", "file_engine"] }
