[package]
name = "eui_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "1"
proc-macro2 = "1"
serde = { version = "1", features = ["derive"], default-features = false }